FROM nginx:1.21.4

COPY build-deploy/nginx.conf /etc/nginx/nginx.conf
COPY build-deploy/proxy_params /etc/nginx/proxy_params
COPY build-deploy/wsgi_proxy /etc/nginx/sites-available/wsgi_proxy

RUN mkdir -p /etc/nginx/sites-enabled
RUN ln -s /etc/nginx/sites-available/wsgi_proxy /etc/nginx/sites-enabled/

CMD nginx -g 'daemon off;'
