# Generated by Django 4.0.4 on 2022-05-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(max_length=32, verbose_name='통화코드')),
                ('cur_nm', models.CharField(max_length=64, verbose_name='국가/통화명')),
                ('ttb', models.FloatField(max_length=64, verbose_name='살 때')),
                ('tts', models.FloatField(max_length=64, verbose_name='팔 때')),
                ('deal_bas_r', models.FloatField(max_length=64, verbose_name='매매 기준율')),
            ],
        ),
    ]
