# Generated by Django 4.0.4 on 2022-05-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=128)),
                ('kor_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=32)),
                ('eng_name', models.CharField(max_length=64)),
                ('kor_name', models.CharField(max_length=32)),
                ('country_id', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, related_name='country', to='cities.country')),
            ],
        ),
    ]
