# Generated by Django 4.0.4 on 2022-07-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.CharField(max_length=32, verbose_name='도시코드'),
        ),
        migrations.AlterField(
            model_name='city',
            name='eng_name',
            field=models.CharField(max_length=64, verbose_name='영문명'),
        ),
        migrations.AlterField(
            model_name='city',
            name='kor_name',
            field=models.CharField(max_length=32, verbose_name='한글명'),
        ),
        migrations.AlterField(
            model_name='country',
            name='eng_name',
            field=models.CharField(max_length=128, verbose_name='영문명'),
        ),
        migrations.AlterField(
            model_name='country',
            name='kor_name',
            field=models.CharField(max_length=128, verbose_name='한글명'),
        ),
    ]
